### PR TITLE
Attempt to get opentelemetry 0.24 working

### PR DESCRIPTION
**Pull request by hardbyte**
Currently not propagating across services (which is working in main branch).

image

See
- https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/CHANGELOG.md#v0170
- https://github.com/tokio-rs/tracing-opentelemetry/pull/155/files
- https://github.com/TrueLayer/reqwest-middleware/tree/main/reqwest-tracing

Could be related to this issue - https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/issues/148
Although I tried setting the tracer level to INFO and TRACE.

### CODE REVIEW

**Comment by hardbyte** [comment]
PR just to solicit help with why the trace propagation no longer works after updating to 0.24.

Not planning to merge until reqwest-middleware is released - https://github.com/TrueLayer/reqwest-middleware/pull/171

**Comment by mladedav** [comment]
The propagation doesn't work exactly because `reqwest-tracing` uses different `tracing-opentelemetry` from the verison you're using. The problem is that `tracing-opentelemetry` adds information to the spans but `reqwest-tracing` can't read it because it looks for different `OtelData` from different version of `tracing-opentelemetry` which isn't there.

Once `reqwest-tracing` is updated, propagation should work again. You can verify that with patching the dependency from git.

**Comment by hardbyte** [comment]
Thank you very much for the pointer @mladedav - really appreciate it. I had used an upstream git revision of reqwest-tracing and middleware but I suspect it the same issue for `axum-tracing-opentelemetry` via its [workspace cargo file](https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/blob/main/Cargo.toml#L26), as it specifies  `opentelemetry` and `opentelemetry_sdk` at version 0.23, and  = `tracing-opentelemetry` at 0.24.

I'll see about updating the versions in `axum-tracing-opentelemetry` to see if they can all got along.

**Comment by hardbyte** [comment]
Ok that was it - with a very hacky [fork of axum-tracing-opentelemetry](https://github.com/hardbyte/tracing-opentelemetry-instrumentation-sdk) everything works again:

image

**Comment by davidB** [comment]
You should have only one version of opentelemetry in your dependency's graph, because opentelemetry::global used static variables to store `tracer_provider`, `propagator`, ... So several versions imply several contexts, tracers,... 
(tips on some of my projects I added a check (as part of the ci) into the dependency graph to enforce the one version of opentelemetry. Sorry I don't have access to the command, currently)

**Comment by davidB** [comment]
FYI, I release new version of crates at https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk with support of opentelemetry 0.24

**Comment by hardbyte** [comment]
> You should have only one version of opentelemetry in your dependency's graph, because opentelemetry::global used static variables to store `tracer_provider`, `propagator`, ... So several versions imply several contexts, tracers,... (tips on some of my projects I added a check (as part of the ci) into the dependency graph to enforce the one version of opentelemetry. Sorry I don't have access to the command, currently)

Yes that's a bit of a trap! I'd managed to find that using `cargo tree`. Will update this branch to use the new `tracing-opentelemetry-instrumentation-sdk` now. Thanks!

**Pull request merged**
